default_install_hook_types:
  - pre-commit
  - commit-msg
repos:
#  - repo: https://github.com/dnephin/pre-commit-golang
#    rev: 754b74671bbdd30059a778d480342a037aff9cd7
#    hooks:
#      - id: go-imports
#      - id: go-mod-tidy

  - repo: https://github.com/tekwizely/pre-commit-golang
    rev: 645165368711be670d1945c15060e746f5ed15c6
    hooks:
#      - id: go-imports
#      - id: go-mod-tidy
# TODO: Doesn't work, use below hook from https://github.com/golangci/golangci-lint
      - id: go-lint
#      - id: go-critic
#      - id: go-sec-repo-pkg
#        args:
#          - "-exclude-generated"

#  - repo: https://github.com/golangci/golangci-lint
#    rev: v1.45.2
#    hooks:
#      - id: golangci-lint
#        args:
#          - "--timeout=3m"
#  - repo: https://github.com/commitizen-tools/commitizen
#    rev: v2.24.0
#    hooks:
#      - id: commitizen
#        stages: [commit-msg]
#  - repo: https://github.com/dhis2-sre/im-tooling
#    rev: v0.0.2
#    hooks:
#      - id: swagger-validation
