apiVersion: skaffold/v2beta25
kind: Config
build:
  artifacts:
    - image: dhis2/instance-database-manager
deploy:
  statusCheckDeadlineSeconds: 120
  helm:
    releases:
      - name: im-database-manager-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        chartPath: helm/chart
        artifactOverrides:
          image: dhis2/instance-database-manager
        imageStrategy:
          helm: { }
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/values.yaml
          - helm/data/values/{{ .ENVIRONMENT }}/values.yaml

      - name: im-database-manager-postgresql-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: postgresql
        repo: https://charts.bitnami.com/bitnami
        version: 11.0.4
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/postgresql.yaml

      - name: im-database-manager-rabbitmq-{{ .ENVIRONMENT }}
        namespace: instance-manager-{{ .ENVIRONMENT }}
        createNamespace: true
        remoteChart: rabbitmq
        repo: https://charts.bitnami.com/bitnami
        version: 16.4.0
        useHelmSecrets: true
        valuesFiles:
          - helm/data/secrets/{{ .ENVIRONMENT }}/rabbitmq.yaml
