consumes:
- application/json
definitions:
  CreateDatabaseRequest:
    properties:
      groupId:
        format: uint64
        type: integer
        x-go-name: GroupId
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/dhis2-sre/im-database-manager/pkg/database
  Database:
    properties:
      CreatedAt:
        format: date-time
        type: string
      DeletedAt:
        $ref: '#/definitions/DeletedAt'
      GroupID:
        format: uint64
        type: integer
      ID:
        format: uint64
        type: integer
      InstanceID:
        format: uint64
        type: integer
      Name:
        type: string
      UpdatedAt:
        format: date-time
        type: string
      Url:
        type: string
    type: object
    x-go-package: github.com/dhis2-sre/im-database-manager/pkg/model
  DeletedAt:
    $ref: '#/definitions/NullTime'
  LockDatabaseRequest:
    properties:
      instanceId:
        format: uint64
        type: integer
        x-go-name: InstanceId
    type: object
    x-go-package: github.com/dhis2-sre/im-database-manager/pkg/database
  Model:
    description: |-
      Model a basic GoLang struct which includes the following fields: ID, CreatedAt, UpdatedAt, DeletedAt
      It may be embedded into your model or you may build your own model without it
      type User struct {
      gorm.Model
      }
    properties:
      CreatedAt:
        format: date-time
        type: string
      DeletedAt:
        $ref: '#/definitions/DeletedAt'
      ID:
        format: uint64
        type: integer
      UpdatedAt:
        format: date-time
        type: string
    type: object
    x-go-package: gorm.io/gorm
  NullTime:
    description: |-
      NullTime implements the Scanner interface so
      it can be used as a scan destination, similar to NullString.
    properties:
      Time:
        format: date-time
        type: string
      Valid:
        type: boolean
    title: NullTime represents a time.Time that may be null.
    type: object
    x-go-package: database/sql
  UpdateDatabaseRequest:
    properties:
      groupId:
        format: uint64
        type: integer
        x-go-name: GroupId
      name:
        type: string
        x-go-name: Name
    type: object
    x-go-package: github.com/dhis2-sre/im-database-manager/pkg/database
info:
  contact:
    email: info@dhis2.org
    url: https://github.com/dhis2-sre/im-database-manager
  description: Database Manager Service as part of the Instance Manager environment
  license:
    name: TODO
  termsOfService: There are no TOS at this moment, use at your own risk we take no
    responsibility
  title: Instance Database Manager Service.
  version: 0.1.0
paths:
  /databases:
    get:
      description: List databases
      operationId: listDatabases
      responses:
        "200":
          description: Database
          schema:
            items:
              $ref: '#/definitions/Database'
            type: array
        "401":
          $ref: '#/responses/Error'
        "403":
          $ref: '#/responses/Error'
        "415":
          $ref: '#/responses/Error'
      security:
      - oauth2: []
    post:
      description: Create database
      operationId: createDatabase
      parameters:
      - description: Create database request body parameter
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/CreateDatabaseRequest'
      responses:
        "202":
          description: Database
          schema:
            $ref: '#/definitions/Database'
        "401":
          $ref: '#/responses/Error'
        "403":
          $ref: '#/responses/Error'
        "415":
          $ref: '#/responses/Error'
      security:
      - oauth2: []
  /databases/{id}:
    delete:
      description: Delete database by id
      operationId: deleteDatabaseById
      parameters:
      - format: uint64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "202":
          description: ""
        "401":
          $ref: '#/responses/Error'
        "403":
          $ref: '#/responses/Error'
        "415":
          $ref: '#/responses/Error'
      security:
      - oauth2: []
    get:
      description: Find database by id
      operationId: findDatabaseById
      parameters:
      - format: uint64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      responses:
        "200":
          description: Database
          schema:
            $ref: '#/definitions/Database'
        "401":
          $ref: '#/responses/Error'
        "403":
          $ref: '#/responses/Error'
        "415":
          $ref: '#/responses/Error'
      security:
      - oauth2: []
    put:
      description: Update database by id
      operationId: updateDatabaseById
      parameters:
      - format: uint64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      - description: Update database request body parameter
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/UpdateDatabaseRequest'
      responses:
        "200":
          description: ""
        "401":
          $ref: '#/responses/Error'
        "403":
          $ref: '#/responses/Error'
        "415":
          $ref: '#/responses/Error'
      security:
      - oauth2: []
  /databases/{id}/lock:
    delete:
      description: Unlock database by id
      operationId: unlockDatabaseById
      parameters:
      - format: uint64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      - description: Lock/unlock database request body parameter
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/LockDatabaseRequest'
      responses:
        "202":
          description: ""
        "401":
          $ref: '#/responses/Error'
        "403":
          $ref: '#/responses/Error'
        "415":
          $ref: '#/responses/Error'
      security:
      - oauth2: []
    post:
      description: Lock database by id
      operationId: lockDatabaseById
      parameters:
      - format: uint64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      - description: Lock/unlock database request body parameter
        in: body
        name: Body
        required: true
        schema:
          $ref: '#/definitions/LockDatabaseRequest'
      responses:
        "200":
          description: Database
          schema:
            $ref: '#/definitions/Database'
        "401":
          $ref: '#/responses/Error'
        "403":
          $ref: '#/responses/Error'
        "409":
          $ref: '#/responses/Error'
        "415":
          $ref: '#/responses/Error'
      security:
      - oauth2: []
  /databases/{id}/upload:
    post:
      description: Upload database
      operationId: uploadDatabase
      parameters:
      - format: uint64
        in: path
        name: id
        required: true
        type: integer
        x-go-name: ID
      - description: Upload database request body parameter
        in: formData
        name: File
        required: true
        type: file
      responses:
        "201":
          description: Database
          schema:
            $ref: '#/definitions/Database'
        "401":
          $ref: '#/responses/Error'
        "403":
          $ref: '#/responses/Error'
        "415":
          $ref: '#/responses/Error'
      security:
      - oauth2: []
produces:
- application/json
responses:
  Error:
    description: ""
securityDefinitions:
  oauth2:
    flow: password
    tokenUrl: /not-valid--endpoint-is-served-from-the-im-user-service
    type: oauth2
swagger: "2.0"
