// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// DeleteDatabaseByIDReader is a Reader for the DeleteDatabaseByID structure.
type DeleteDatabaseByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteDatabaseByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewDeleteDatabaseByIDAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewDeleteDatabaseByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewDeleteDatabaseByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewDeleteDatabaseByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewDeleteDatabaseByIDUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewDeleteDatabaseByIDAccepted creates a DeleteDatabaseByIDAccepted with default headers values
func NewDeleteDatabaseByIDAccepted() *DeleteDatabaseByIDAccepted {
	return &DeleteDatabaseByIDAccepted{}
}

/*
DeleteDatabaseByIDAccepted describes a response with status code 202, with default header values.

DeleteDatabaseByIDAccepted delete database by Id accepted
*/
type DeleteDatabaseByIDAccepted struct {
}

func (o *DeleteDatabaseByIDAccepted) Error() string {
	return fmt.Sprintf("[DELETE /databases/{id}][%d] deleteDatabaseByIdAccepted ", 202)
}

func (o *DeleteDatabaseByIDAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDatabaseByIDUnauthorized creates a DeleteDatabaseByIDUnauthorized with default headers values
func NewDeleteDatabaseByIDUnauthorized() *DeleteDatabaseByIDUnauthorized {
	return &DeleteDatabaseByIDUnauthorized{}
}

/*
DeleteDatabaseByIDUnauthorized describes a response with status code 401, with default header values.

DeleteDatabaseByIDUnauthorized delete database by Id unauthorized
*/
type DeleteDatabaseByIDUnauthorized struct {
}

func (o *DeleteDatabaseByIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /databases/{id}][%d] deleteDatabaseByIdUnauthorized ", 401)
}

func (o *DeleteDatabaseByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDatabaseByIDForbidden creates a DeleteDatabaseByIDForbidden with default headers values
func NewDeleteDatabaseByIDForbidden() *DeleteDatabaseByIDForbidden {
	return &DeleteDatabaseByIDForbidden{}
}

/*
DeleteDatabaseByIDForbidden describes a response with status code 403, with default header values.

DeleteDatabaseByIDForbidden delete database by Id forbidden
*/
type DeleteDatabaseByIDForbidden struct {
}

func (o *DeleteDatabaseByIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /databases/{id}][%d] deleteDatabaseByIdForbidden ", 403)
}

func (o *DeleteDatabaseByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDatabaseByIDNotFound creates a DeleteDatabaseByIDNotFound with default headers values
func NewDeleteDatabaseByIDNotFound() *DeleteDatabaseByIDNotFound {
	return &DeleteDatabaseByIDNotFound{}
}

/*
DeleteDatabaseByIDNotFound describes a response with status code 404, with default header values.

DeleteDatabaseByIDNotFound delete database by Id not found
*/
type DeleteDatabaseByIDNotFound struct {
}

func (o *DeleteDatabaseByIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /databases/{id}][%d] deleteDatabaseByIdNotFound ", 404)
}

func (o *DeleteDatabaseByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteDatabaseByIDUnsupportedMediaType creates a DeleteDatabaseByIDUnsupportedMediaType with default headers values
func NewDeleteDatabaseByIDUnsupportedMediaType() *DeleteDatabaseByIDUnsupportedMediaType {
	return &DeleteDatabaseByIDUnsupportedMediaType{}
}

/*
DeleteDatabaseByIDUnsupportedMediaType describes a response with status code 415, with default header values.

DeleteDatabaseByIDUnsupportedMediaType delete database by Id unsupported media type
*/
type DeleteDatabaseByIDUnsupportedMediaType struct {
}

func (o *DeleteDatabaseByIDUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[DELETE /databases/{id}][%d] deleteDatabaseByIdUnsupportedMediaType ", 415)
}

func (o *DeleteDatabaseByIDUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
