// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewFindDatabaseByIDParams creates a new FindDatabaseByIDParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewFindDatabaseByIDParams() *FindDatabaseByIDParams {
	return &FindDatabaseByIDParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewFindDatabaseByIDParamsWithTimeout creates a new FindDatabaseByIDParams object
// with the ability to set a timeout on a request.
func NewFindDatabaseByIDParamsWithTimeout(timeout time.Duration) *FindDatabaseByIDParams {
	return &FindDatabaseByIDParams{
		timeout: timeout,
	}
}

// NewFindDatabaseByIDParamsWithContext creates a new FindDatabaseByIDParams object
// with the ability to set a context for a request.
func NewFindDatabaseByIDParamsWithContext(ctx context.Context) *FindDatabaseByIDParams {
	return &FindDatabaseByIDParams{
		Context: ctx,
	}
}

// NewFindDatabaseByIDParamsWithHTTPClient creates a new FindDatabaseByIDParams object
// with the ability to set a custom HTTPClient for a request.
func NewFindDatabaseByIDParamsWithHTTPClient(client *http.Client) *FindDatabaseByIDParams {
	return &FindDatabaseByIDParams{
		HTTPClient: client,
	}
}

/*
FindDatabaseByIDParams contains all the parameters to send to the API endpoint

	for the find database by Id operation.

	Typically these are written to a http.Request.
*/
type FindDatabaseByIDParams struct {

	// ID.
	//
	// Format: uint64
	ID uint64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the find database by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindDatabaseByIDParams) WithDefaults() *FindDatabaseByIDParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the find database by Id params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *FindDatabaseByIDParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the find database by Id params
func (o *FindDatabaseByIDParams) WithTimeout(timeout time.Duration) *FindDatabaseByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the find database by Id params
func (o *FindDatabaseByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the find database by Id params
func (o *FindDatabaseByIDParams) WithContext(ctx context.Context) *FindDatabaseByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the find database by Id params
func (o *FindDatabaseByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the find database by Id params
func (o *FindDatabaseByIDParams) WithHTTPClient(client *http.Client) *FindDatabaseByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the find database by Id params
func (o *FindDatabaseByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithID adds the id to the find database by Id params
func (o *FindDatabaseByIDParams) WithID(id uint64) *FindDatabaseByIDParams {
	o.SetID(id)
	return o
}

// SetID adds the id to the find database by Id params
func (o *FindDatabaseByIDParams) SetID(id uint64) {
	o.ID = id
}

// WriteToRequest writes these params to a swagger request
func (o *FindDatabaseByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param id
	if err := r.SetPathParam("id", swag.FormatUint64(o.ID)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
