// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/dhis2-sre/im-database-manager/swagger/sdk/models"
)

// UploadDatabaseReader is a Reader for the UploadDatabase structure.
type UploadDatabaseReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *UploadDatabaseReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewUploadDatabaseCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 401:
		result := NewUploadDatabaseUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewUploadDatabaseForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewUploadDatabaseNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 415:
		result := NewUploadDatabaseUnsupportedMediaType()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		return nil, runtime.NewAPIError("response status code does not match any response statuses defined for this endpoint in the swagger spec", response, response.Code())
	}
}

// NewUploadDatabaseCreated creates a UploadDatabaseCreated with default headers values
func NewUploadDatabaseCreated() *UploadDatabaseCreated {
	return &UploadDatabaseCreated{}
}

/*
UploadDatabaseCreated describes a response with status code 201, with default header values.

Database
*/
type UploadDatabaseCreated struct {
	Payload *models.Database
}

func (o *UploadDatabaseCreated) Error() string {
	return fmt.Sprintf("[POST /databases][%d] uploadDatabaseCreated  %+v", 201, o.Payload)
}
func (o *UploadDatabaseCreated) GetPayload() *models.Database {
	return o.Payload
}

func (o *UploadDatabaseCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Database)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewUploadDatabaseUnauthorized creates a UploadDatabaseUnauthorized with default headers values
func NewUploadDatabaseUnauthorized() *UploadDatabaseUnauthorized {
	return &UploadDatabaseUnauthorized{}
}

/*
UploadDatabaseUnauthorized describes a response with status code 401, with default header values.

UploadDatabaseUnauthorized upload database unauthorized
*/
type UploadDatabaseUnauthorized struct {
}

func (o *UploadDatabaseUnauthorized) Error() string {
	return fmt.Sprintf("[POST /databases][%d] uploadDatabaseUnauthorized ", 401)
}

func (o *UploadDatabaseUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadDatabaseForbidden creates a UploadDatabaseForbidden with default headers values
func NewUploadDatabaseForbidden() *UploadDatabaseForbidden {
	return &UploadDatabaseForbidden{}
}

/*
UploadDatabaseForbidden describes a response with status code 403, with default header values.

UploadDatabaseForbidden upload database forbidden
*/
type UploadDatabaseForbidden struct {
}

func (o *UploadDatabaseForbidden) Error() string {
	return fmt.Sprintf("[POST /databases][%d] uploadDatabaseForbidden ", 403)
}

func (o *UploadDatabaseForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadDatabaseNotFound creates a UploadDatabaseNotFound with default headers values
func NewUploadDatabaseNotFound() *UploadDatabaseNotFound {
	return &UploadDatabaseNotFound{}
}

/*
UploadDatabaseNotFound describes a response with status code 404, with default header values.

UploadDatabaseNotFound upload database not found
*/
type UploadDatabaseNotFound struct {
}

func (o *UploadDatabaseNotFound) Error() string {
	return fmt.Sprintf("[POST /databases][%d] uploadDatabaseNotFound ", 404)
}

func (o *UploadDatabaseNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewUploadDatabaseUnsupportedMediaType creates a UploadDatabaseUnsupportedMediaType with default headers values
func NewUploadDatabaseUnsupportedMediaType() *UploadDatabaseUnsupportedMediaType {
	return &UploadDatabaseUnsupportedMediaType{}
}

/*
UploadDatabaseUnsupportedMediaType describes a response with status code 415, with default header values.

UploadDatabaseUnsupportedMediaType upload database unsupported media type
*/
type UploadDatabaseUnsupportedMediaType struct {
}

func (o *UploadDatabaseUnsupportedMediaType) Error() string {
	return fmt.Sprintf("[POST /databases][%d] uploadDatabaseUnsupportedMediaType ", 415)
}

func (o *UploadDatabaseUnsupportedMediaType) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}
