apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "im-database-manager.fullname" . }}
  labels:
    {{- include "im-database-manager.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "im-database-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "im-database-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "im-database-manager.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.containerPort }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: {{ .Values.basePath }}/health
              port: http
          readinessProbe:
            httpGet:
              path: {{ .Values.basePath }}/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          envFrom:
            - configMapRef:
                name: {{ include "im-database-manager.fullname" . }}
            - secretRef:
                name: {{ include "im-database-manager.fullname" . }}
          volumeMounts:
            - mountPath: /tmp
              name: tmp
              subPath: tmp
            - mountPath: {{ .Values.dataMountPath }}
              name: data
      volumes:
        - name: tmp
          emptyDir:
            medium: Memory
            sizeLimit: {{ .Values.tmpfsSizeLimit }}
        - name: data
          emptyDir:
            sizeLimit: {{ .Values.dataSizeLimit }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
