kind: Secret
apiVersion: v1
metadata:
  name: {{ include "im-database-manager.fullname" . }}
  labels:
    {{- include "im-database-manager.labels" . | nindent 4 }}
type: Opaque
data:
  DATABASE_USERNAME: {{ .Values.database.username | b64enc }}
  DATABASE_PASSWORD: {{ .Values.database.password | b64enc }}

  RABBITMQ_USERNAME: {{ .Values.rabbitMq.username | b64enc }}
  RABBITMQ_PASSWORD: {{ .Values.rabbitMq.password | b64enc }}
