// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// ExternalDownload external download
//
// swagger:model ExternalDownload
type ExternalDownload struct {

	// database ID
	DatabaseID uint64 `json:"DatabaseID,omitempty"`

	// expiration
	// Format: date-time
	Expiration strfmt.DateTime `json:"Expiration,omitempty"`

	// UUID
	UUID UUID `json:"UUID,omitempty"`
}

// Validate validates this external download
func (m *ExternalDownload) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateExpiration(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateUUID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExternalDownload) validateExpiration(formats strfmt.Registry) error {
	if swag.IsZero(m.Expiration) { // not required
		return nil
	}

	if err := validate.FormatOf("Expiration", "body", "date-time", m.Expiration.String(), formats); err != nil {
		return err
	}

	return nil
}

func (m *ExternalDownload) validateUUID(formats strfmt.Registry) error {
	if swag.IsZero(m.UUID) { // not required
		return nil
	}

	if err := m.UUID.Validate(formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("UUID")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("UUID")
		}
		return err
	}

	return nil
}

// ContextValidate validate this external download based on the context it is used
func (m *ExternalDownload) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateUUID(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *ExternalDownload) contextValidateUUID(ctx context.Context, formats strfmt.Registry) error {

	if err := m.UUID.ContextValidate(ctx, formats); err != nil {
		if ve, ok := err.(*errors.Validation); ok {
			return ve.ValidateName("UUID")
		} else if ce, ok := err.(*errors.CompositeError); ok {
			return ce.ValidateName("UUID")
		}
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (m *ExternalDownload) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ExternalDownload) UnmarshalBinary(b []byte) error {
	var res ExternalDownload
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
