// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SaveDatabaseRequest save database request
//
// swagger:model SaveDatabaseRequest
type SaveDatabaseRequest struct {

	// instance Id
	InstanceID uint64 `json:"instanceId,omitempty"`
}

// Validate validates this save database request
func (m *SaveDatabaseRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this save database request based on context it is used
func (m *SaveDatabaseRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SaveDatabaseRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SaveDatabaseRequest) UnmarshalBinary(b []byte) error {
	var res SaveDatabaseRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
