// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// SaveAsRequest save as request
//
// swagger:model saveAsRequest
type SaveAsRequest struct {

	// TODO: Allow saving to another group, remember to ensure user is member of the other group
	// Group  string `json:"group"`
	Format string `json:"format,omitempty"`

	// TODO: Add InstanceId here rather than as path param?
	// InstanceId uint   `json:"instanceId" binding:"required"`
	Name string `json:"name,omitempty"`
}

// Validate validates this save as request
func (m *SaveAsRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this save as request based on context it is used
func (m *SaveAsRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *SaveAsRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SaveAsRequest) UnmarshalBinary(b []byte) error {
	var res SaveAsRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
