// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// UUID A UUID is a 128 bit (16 byte) Universal Unique IDentifier as defined in RFC
// 4122.
//
// swagger:model UUID
type UUID []uint8

// Validate validates this UUID
func (m UUID) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this UUID based on context it is used
func (m UUID) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
